### ISSUE TITLE
ModuleNotFoundError: No module named 'extensions.animator'

### ISSUE THREAD

**Issue by Northloop** [Animator-Anon/animator_extension#1]
Hey, I've tried to install your extension, but I get this error when I run the web-ui.bat  

File "C:\stable-diffusion-webui\modules\scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\extensions\animator_extension\scripts\animator.py", line 14, in <module>
    from extensions.animator.scripts.functions import prepwork, sequential, loopback, export
ModuleNotFoundError: No module named 'extensions.animator'

**Comment by Animator-Anon** [comment]
Ah you are right.. You could rename the folder animator_extension to just animator, that would fix it. I need to figure out how to make this work.

**Comment by Animator-Anon** [comment]
Should be fixed now. If you renamed the folder as I mentioned above, rename it back and then upate.
Or delete and reinstall.

**Comment by Northloop** [comment]
Thanks!
