### ISSUE TITLE
Have problem

### ISSUE THREAD

**Issue by Disuma** [Animator-Anon/animator_extension#10]
![image](https://user-images.githubusercontent.com/37750561/224116416-12d9e071-cc41-4f16-99d2-f7331fb5420f.png)

**Comment by RagingFlames** [comment]
![image](https://user-images.githubusercontent.com/28068199/224450387-80554fbc-d6f9-4d53-b70e-49ddd42d7e7b.png)
Same issue with similar line numbers.

**Comment by Animator-Anon** [comment]
Duplicate of #5
