### ISSUE TITLE
How exactly does one utilize keyframes?

### ISSUE THREAD

**Issue by gmod64bit** [Animator-Anon/animator_extension#12]
`time_s | transform | zoom | x_shift | y_shift | rotation
`
do I just add

`time_s | transform | zoom **2** | x_shift | y_shift | rotation`

and it will start zooming? I am very confused on this. Any help would be sincerely appreciated. Sorry for the noobness.

And thank you for this incredible project!

**Comment by Animator-Anon** [comment]
Check the main readme, the examples section. 
Hopefully that makes it clearer!

**Comment by gmod64bit** [comment]
> Check the main readme, the examples section. Hopefully that makes it clearer!

Thank you, that has cleared up a lot. One more question if you don't mind, what are the "poor quality | high quality" tags meaning?

**Comment by Animator-Anon** [comment]
0 | transform | 1.2 | 0 | 0 | 0

**Comment by gmod64bit** [comment]
> 0 | transform | 1.2 | 0 | 0 | 0

Thank you!!! God this is incredible. I have one final noob question if you wouldn't mind, I swear. Can one make the "camera" constanting panning to the left? Make it look like the video is turning to the left?

**Comment by Animator-Anon** [comment]
0 | transform | 1.0 | 100 | 0 | 0

Maybe something like that? Or maybe a negative number, I forget. It will move the image 100 pixels per second and fill in the blanks.

**Comment by gmod64bit** [comment]
> 0 | transform | 1.0 | 100 | 0 | 0
> 
> Maybe something like that? Or maybe a negative number, I forget. It will move the image 100 pixels per second and fill in the blanks.

You're amazing. Thank you!
