### ISSUE TITLE
Possible bugs in seed travel mode

### ISSUE THREAD

**Issue by Meru** [Animator-Anon/animator_extension#13]
Given the keyframes below and animation of 6 seconds at 6 fps, my observations:

What I expected: After reaching seed `33333333` at around 3rd second, whatever process exits or it keeps repeating the same image for 3 more seconds
What seems to be happening: it ignores the value 3 and is trying to reach seed `33333333` in 5 seconds to fill the whole video

Additional observation:
seed `11111111` travels to seed `22222222` by a factor of `0.0` to `1.0`. So far so good. But...
`seed 11111111 -> 22222222 @ 1.0` seems to be equal to `seed 22222222 -> 33333333 @ 0.0`, which results in a duplicated frames in-between of the animation.

Also, for whatever reason, last frame/image of the animation is always missing, even though is is present in the csv.
AlsoAlso, output is being saved in SD root directory. Consider moving it to at least "output" folder.

```
0 | prompt | super nice prompt
0 | seed | 11111111
1 | seed | 22222222
3 | seed | 33333333
```

**Comment by Animator-Anon** [comment]
Yes this does appear to happen. I am going to have to go over all the seed logic again, may take a while.

**Comment by Animator-Anon** [comment]
I tweaked the logic a bit and now it seems to work a bit better.
