### ISSUE TITLE
"denoise" keyframe seems to be broken

### ISSUE THREAD

**Issue by leobut** [Animator-Anon/animator_extension#14]
I have a long keyframe list that contains a lot of denoise changes and it looks like denoise change is not working. You can tests this by putting "Denoising Strength" on the UI to 1 and then adding something like this as keyframes:

0.0 | denoise | 0.0
1.0 | denoise | 0.1
2.0 | denoise | 0.2

You will see that the denoise from the UI is taken for image generation instead of the defined keyframe denoise.
This is also visible in the console output where you are running a1111. You can see, that it's doing the full amount of sampling steps every iteration instead of adapting to a changing denoise value.

**Comment by Animator-Anon** [comment]
It was not yet implemented, should be fixed now.

**Comment by leobut** [comment]
Awesome, works like a charm now! 😄
