### ISSUE TITLE
"template" does no longer overwrite "Use pos prompts from style" and "Use neg prompts from style"

### ISSUE THREAD

**Issue by leobut** [Animator-Anon/animator_extension#16]
First of all: Big thank you for the last update! ❤️ 

I noticed one thing:
With the last change, the behavior of the template command has changed. I am not sure if it was intended or not.

The two styles "Use pos prompts from style" and "Use neg prompts from style" are now appended to the template even if the checkbox for "Prompt Interpolation" is disabled.

Workaround:
1. Go to txt2img
2. Have empty pos. and neg. prompts
3. Save new style as e.g. "None"
4. Restart automatic1111
5. Go to Animator and select the new "None" style as value for both "Use pos prompts from style" and "Use neg prompts from style"

**Comment by Animator-Anon** [comment]
Hmm who knows what happened, spaghetti code. I notice some other issues so will go through it again.
Do you mean the term "Use pos prompts from style" is literally appended to the prompts? That shouldn't happen.
Also, prompt interpolation shouldn't matter here, the prompts should be set the same at the keyframe times regardless. It just tries to interpolate the prompts in the frames between.

**Comment by leobut** [comment]
you can see that they are concatenated in the keyframes.csv, but I would look at this as a low-prio bug as there is an easy workaround 😄

**Comment by Animator-Anon** [comment]
I think I might have misunderstood, but the styles will be applied if you have them selected. It doesn't matter if the prompt_interpolation checkbox is checked, it isn't related to styles at all. If you don't want styles applied, select None or the blank entry, depending on the version of Automatic UI. 
Are you saying you don't have any other options in the list than valid styles, so the only way to avoid them being applied is to create a blank style and select that? This might be more of an issue with the UI, not my extension. You could try clear out the styles (after backing up the file) and see if that helps, then copy the styles back into the main file from the backup one.

**Comment by leobut** [comment]
The thing it that before your lates update, I was able to use the "template" keyframe to overwrite whatever was selected in the styles dropdown, but this has now changed.

> Are you saying you don't have any other options in the list than valid styles, so the only way to avoid them being applied is to create a blank style and select that? This might be more of an issue with the UI, not my extension.

Yes, this is exactly the case for and your little guide helped me fix it, thanks again! You may close this ticket as resolved if you like.
