### ISSUE TITLE
Interpolated frames not generated in 'interpolated_frames' folder

### ISSUE THREAD

**Issue by mgmandahl** [Animator-Anon/animator_extension#18]
I am using the animator_extension along with frame_interpolation. However, I encountered an issue where the interpolated_frames folder is created, but no interpolated frames are generated within the folder.

The process runs without any error messages, and I receive the following output:

shell
Copy code
100%|█████████████████████████████████████████████████████████████| 149/149 [14:00<00:00,  5.64s/it]
100%|█████████████████████████████████████████████████████████████| 299/299 [00:35<00:00,  8.45it/s]
I0413 19:51:52.540082  4964 interpolator_cli.py:149] Output frames saved in D:\AI\stable-diffusion-webui\outputs\text2video\20230413192359/interpolated_frames

However, the interpolated_frames folder is empty.

I have verified that FFMPEG is installed and the environment variables are set. I also confirmed the correct path to the saved model.

Operating System: WIN 10
Python version: 3.10.8
FFMPEG version: ffmpeg version 2023-04-12-git-1179bb703e-full_build-[www.gyan.dev](http://www.gyan.dev/) (built with gcc 12.2.0)

Please let me know if there are any additional steps or configurations I need to consider. Thank you!

**Comment by Animator-Anon** [comment]
It might be a misleading statement, this happens:

- WebUi makes a bunch of frames,
- These are used as the source frames for the FILM interpolation,
- The output frames from that are are saved in the interpolated_frames folder,
- The original frames are deleted,
- The interpolated frames are moved to the output folder.

You should see a noticeable difference in the output running it twice with FILM interpolation turned off and on.
