### ISSUE TITLE
Selected Film Interpolation- cannot find

### ISSUE THREAD

**Issue by egormly** [Animator-Anon/animator_extension#2]
I selected Film Interpolation and when it was finished I get this error in the CMD

FILM could not be found in this folder: C:/AI/frame_interpolation

I have the auto installed on D in it's own folder. I do not see a setting to change it.

**Comment by Animator-Anon** [comment]
Yes this extension doesn't come with the FILM interpolation built in, you need to install it seperately and create a bat file this script can call to run it.
From the readme:

FILM batch or script file, including full path
Full path to a batch file that can be called for FILM interpolation. The bat file will do what ever is required to make the FILM interpolation happening. The bat file must take two arguments. The first one being the GLOB path and pattern for the input files, and the second being the number of passes or times to interpolate. This isn't the same as adding n frames inbetween every source frame, but the number of times to add frames between every frame. This works out to be adding 2^(n-1) frames between every source frame? Don't quote me on that. For example, my bat file:
```
call %USERPROFILE%\miniconda3\condabin\conda.bat activate ldm
python -m eval.interpolator_cli --pattern "%1" --model_path pretrained_models\film_net\Style\saved_model --times_to_interpolate %2
call %USERPROFILE%\miniconda3\condabin\conda.bat deactivate
```

**Comment by Animator-Anon** [comment]
Did you figure this out?

**Comment by egormly** [comment]
yes thank you :)
