### ISSUE TITLE
check_gallery is not defined ReferenceError: check_gallery is not defined in animator.js

### ISSUE THREAD

**Issue by mikecastrodemaria** [Animator-Anon/animator_extension#23]
Hello, javascript error that make crash SD Web UI :

this is the consol output :
check_gallery is not defined ReferenceError: check_gallery is not defined
    <anonymous> http://127.0.0.1:7860/file=/xxx/xxx/xxx/extensions/animator_extension/javascript/animator.js?1683026397.73:45
    runCallback http://127.0.0.1:7860/file=/xxx/xxx/xxx/script.js?1680005394.0:38
    executeCallbacks http://127.0.0.1:7860/file=/xxx/xxx/xxx/script.js?1680005394.0:44
    executeCallbacks http://127.0.0.1:7860/file=/xxx/xxx/xxx/script.js?1680005394.0:44
    mutationObserver http://127.0.0.1:7860/file=/xxx/xxx/xxx/script.js?1680005394.0:56
    MutationCallback* http://127.0.0.1:7860/file=/xxx/xxx/xxx/script.js?1680005394.0:50
    EventListener.handleEvent* http://127.0.0.1:7860/file=/xxx/xxx/xxx/script.js?1680005394.0:49
script.js:40:40
    runCallback http://127.0.0.1:7860/file=/xxx/xxx/xxx/script.js?1680005394.0:40
    executeCallbacks http://127.0.0.1:7860/file=/xxx/xxx/xxx/script.js?1680005394.0:44
    executeCallbacks http://127.0.0.1:7860/file=/xxx/xxx/xxx/script.js?1680005394.0:44
    mutationObserver http://127.0.0.1:7860/file=/xxx/xxx/xxx/script.js?1680005394.0:56
    (Async: MutationCallback)
    <anonymous> http://127.0.0.1:7860/file=/xxx/xxx/xxx/script.js?1680005394.0:50
    (Async: EventListener.handleEvent)
    <anonymous> http://127.0.0.1:7860/file=/xxx/xxx/xxx/script.js?1680005394.0:49

**Comment by Animator-Anon** [comment]
I think i'll just comment that bit out, I don't even know what it does.

**Comment by Animator-Anon** [comment]
Probably some legacy code thing that has been removed. Is it fixed?

**Comment by mikecastrodemaria** [comment]
No more JS error output thanks, juste the model loader that seem run infinite with the extension activated. 2/3 of WUI extensions break this it seem ...

**Comment by Animator-Anon** [comment]
Are you running on exotic hardware or OS? I only test on windows.

**Comment by mikecastrodemaria** [comment]
On MacOS M1 MB pro // firefox

**Comment by Animator-Anon** [comment]
Ah I have no idea how well it works on Mac, I don't have one.

**Comment by mikecastrodemaria** [comment]
> Ah I have no idea how well it works on Mac, I don't have one.

It's like a linux, just the M1 arm64 arch changes things. You like I'll give you some tech info about version and libs ?

**Comment by Animator-Anon** [comment]
If the main UI works, my script should work. unless something specific to my extension is broken, such as paths not working, or ffmpeg not working, I am not too concerned.
