### ISSUE TITLE
Animator is using an old prompt.

### ISSUE THREAD

**Issue by Kuinox** [Animator-Anon/animator_extension#25]
So basically, the animator tab is using a very old prompt I made a few months ago, before I installed this extension.  
Where do I set this prompt ?  
Even when I set `Positive Prompts` it still mix with the very old prompt.

**Comment by Animator-Anon** [comment]
It might be related to the template. I would create an empty template called None with no prompts in it.

**Comment by Kuinox** [comment]
Mhhh, sorry where can I see the templates/create ones ?

**Comment by Animator-Anon** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#styles

**Comment by Kuinox** [comment]
Indeed the prompt was there, thanks!
