### ISSUE TITLE
REQUEST: making animator a part of Img to Img

### ISSUE THREAD

**Issue by filliptm** [Animator-Anon/animator_extension#26]
My idea here is that theres a lot of things i love about Animator, but i cant use it in conjunction with all the other user useful features in auto. 

if animator was a drop down extension under the img to img tab, it would allow users to use things such as control net, dynamic thresholding, and any other scrip or extension in the img to img tab

**Comment by Animator-Anon** [comment]
It started out as a script that could be selected from these tabs:
https://github.com/Animator-Anon/Animator
This hasn't been tested or updated in a while, might be broken.
