### ISSUE TITLE
Re-run with same initial parameters 

### ISSUE THREAD

**Issue by pandrani** [Animator-Anon/animator_extension#28]
Hi there! Really love this extension. Thanks for your work on it. 

Is there a way to start with the same initial settings but adjust the Animation parameters so I can tweak the result without getting a totally different video? When I try I get a different starting picture even though I’ve typed in the seed. I am sure I’m missing something. 

Thanks,
Peter

**Comment by Animator-Anon** [comment]
Sounds like the seed is randomising. You should be able to type one into the uI or specify an initial seed at time 0, and it should increment it every frame. You can verify this by looking at the .csv file in the output folder in openoffice calc or something similar.
Let me know if this isn't happening properly, I probably broke it.

**Comment by Animator-Anon** [comment]
Any update?
