### ISSUE TITLE
Animator won't load

### ISSUE THREAD

**Issue by scoobiekw** [Animator-Anon/animator_extension#3]
Updated the extension today, restarted UI and Animator tab is missing.

console output

`Error loading script: animator.py
Traceback (most recent call last):
  File "C:\Users\steve\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Users\steve\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Users\steve\stable-diffusion-webui\extensions\animator_extension\scripts\animator.py", line 13, in <module>
    from modules import script_callbacks, shared, sd_models, scripts, ui_common
ImportError: cannot import name 'ui_common' from 'modules' (unknown location)`

**Comment by Animator-Anon** [comment]
Are you running the latest version of Automatic's WebUI?
Do you have a file called ui_common.py in the stable-diffusion-webui\modules folder?
It sounds like this isn't there or is corrupted or something, which should be causing bigger issues.

**Comment by scoobiekw** [comment]
I was surprised that there isn't an update script. I'll do a pull and post back.

Will have time tomorrow to test.

Curious part is all was working until I updated extensions last night.

**Comment by scoobiekw** [comment]
Working after a fresh git pull and reinstall of extensions.

Still curious that upgrading extensions seems to have hosed a base file.
