### ISSUE TITLE
Animator not work on vlad/automatic anymore

### ISSUE THREAD

**Issue by ShmuelRonen** [Animator-Anon/animator_extension#31]
This is from CMD:
Please fix it!!!

09:11:10-949788 ERROR    Error running extension installer:
                         C:\vlad\automatic\extensions\animator_extension\install.py
09:11:29-251989 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter',
                         'seed_travel', 'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg',
                         'SwinIR', 'animator_extension', 'Auto-Photoshop-StableDiffusion-Plugin', 'canvas-zoom',
                         'deforum-for-automatic1111-webui', 'infinite-zoom-automatic1111-webui', 'SD-CN-Animation',
                         'sd-webui-aspect-ratio-helper', 'sd-webui-stablesr', 'TemporalKit', 'unprompted']
09:11:29-271989 INFO     Updating Wiki
09:11:30-230989 WARNING  Setup complete with errors: 1
09:11:30-232987 WARNING  See log file for more details: C:\vlad\automatic\sdnext.log
09:11:30-237989 INFO     Extension preload: 0.0s C:\vlad\automatic\extensions-builtin
09:11:30-239988 INFO     Extension preload: 0.0s C:\vlad\automatic\extensions
09:11:30-257989 INFO     Server arguments: []
No module 'xformers'. Proceeding without it.
09:11:36-278992 INFO     Libraries loaded
09:11:36-283988 INFO     Using data path: C:\vlad\automatic
09:11:36-287987 INFO     Available VAEs: C:\vlad\automatic\models\VAE 2
09:11:36-297992 INFO     Available models: C:\vlad\automatic\models\Stable-diffusion 23
09:11:38-928992 INFO     ControlNet v1.1.224
ControlNet preprocessor location: C:\vlad\automatic\extensions-builtin\sd-webui-controlnet\annotator\downloads
09:11:39-082991 INFO     ControlNet v1.1.224
python_server_full_path:  C:\vlad\automatic\extensions\Auto-Photoshop-StableDiffusion-Plugin\server/python_server
09:11:39-924991 INFO     Libraries loaded
(SETUP) Loading Unprompted v9.2.0 by Therefore Games
(SETUP) Initializing Unprompted object...
(SETUP) Loading configuration files...
(SETUP) Logging enabled for the following message types: RESULT,ERROR
09:11:40-877993 INFO     Loading UI theme: name=gradio/default style=Auto
09:11:42-554989 ERROR    executing callback: C:\vlad\automatic\extensions\animator_extension\scripts\animator.py
                         ui_tabs_callback: ValueError
┌──────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────┐
│ C:\vlad\automatic\modules\script_callbacks.py:161 in ui_tabs_callback                                             │
│                                                                                                                   │
│   160 │   │   │   t0 = time.time()                                                                                │
│ > 161 │   │   │   res += c.callback() or []                                                                       │
│   162 │   │   │   timer(t0, c.script, 'ui_tabs')                                                                  │
│                                                                                                                   │
│ C:\vlad\automatic\extensions\animator_extension\scripts\animator.py:392 in on_ui_tabs                             │
│                                                                                                                   │
│   391 │   │   │   │   │   # result_gallery, generation_info if tabname != "extras" else html_i                    │
│ > 392 │   │   │   │   │   aa_gallery, aa_htmlinfo_x, aa_htmlinfo, aa_htmllog = \                                  │
│   393 │   │   │   │   │   │   ui_common.create_output_panel("animator_extension", shared.opts.                    │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ValueError: too many values to unpack (expected 4)

__________

https://github.com/vladmandic/automatic

**Comment by vladmandic** [comment]
extension should use `ui.create_output_panel`, not internall `ui_common.create_output_panel` or i cannot make any internal changes to the core app.

**Comment by Animator-Anon** [comment]
@ShmuelRonen Unfortunately I can't support forks if I have to make changes specific to that fork.
You can fork my repo and make the required changes or just make the change yourself on your local disk to keep running,

**Comment by vladmandic** [comment]
This is not fork specific, this is valid for A1111 as well.

**Comment by Animator-Anon** [comment]
@vladmandic @ShmuelRonen 
Yes you are right. I tried it the other night and it didn't work, because I hadn't imported ui.
Should be fixed now.
