### ISSUE TITLE
Most efforts come out blurry

### ISSUE THREAD

**Issue by gbushnell121** [Animator-Anon/animator_extension#33]
I am at a loss of what to do here and am looking for direction. I am getting somewhat predicable results, but not in the way I'd like. 9/10 times the output becomes blurry or even blurs and distorts my initial image right off the bat. Tonight it worked for like 3 iterations in a row but I kept ending and tweaking it, and on the fourth tweak, it started to be blurry again. So now I am back to square one. lol 

If anyone knows what could be causing this or what I can do to fix it. All of my tweaks were just one simple param tweak like step count.

Here is the settings and keyframes for one that didn't come out blurry:
 [keyframes.csv](https://github.com/Animator-Anon/animator_extension/files/12392983/keyframes.csv)
[settings.txt](https://github.com/Animator-Anon/animator_extension/files/12392984/settings.txt)

and here they are for one that did turn out blurry:
[settings.txt](https://github.com/Animator-Anon/animator_extension/files/12392985/settings.txt)
[keyframes.csv](https://github.com/Animator-Anon/animator_extension/files/12392986/keyframes.csv)

If you want to test it, here is my init image:
![upscaled American Dream Summer cover formatted for youtube](https://github.com/Animator-Anon/animator_extension/assets/131785453/d820d796-0d13-469b-b685-367e3d62925d)

Appreciate any help! Thanks in advance

**Comment by Animator-Anon** [comment]
I have noticed this working with a source image. The same thing will happen when you take an image and loop it yourself though img2img, It loses much of the finer detail quite quickly. This is one reason why this is sort of a failed experiment with limited utility.
You could try and re-crate the finder detail by upscaling, but it would probably be random every frame.
