### ISSUE TITLE
Rotationg on its axis

### ISSUE THREAD

**Issue by VeteranXT** [Animator-Anon/animator_extension#37]
I was trying to create how something spins...so far it can only spin counter/clock wise.

What i want to do is spin on its axis. Like glob y and x axis. 
Like do a flip or side?
Is this really possible?

**Comment by Animator-Anon** [comment]
With perspective and stuff? They would get nasty since the screen would mostly be filled with empty space padded out and you would lose all of the picture information when it is side on, right?

**Comment by VeteranXT** [comment]
Well you can just it looks like weird. Turns out you need invidual frames made in order to transition..otherwise it just "turns page" effect. But this is not the issue this is just me being stupid.

**Comment by Animator-Anon** [comment]
Link an example of the sort of transform you are thinking of, it might be possible using the experimental and poorly documented perspective transform feature.

**Comment by VeteranXT** [comment]
![istockphoto-1140368765-612x612](https://github.com/Animator-Anon/animator_extension/assets/103519488/3ed42fd0-b5f7-426f-9d04-cfbef8034d4c)
Like this?

**Comment by Animator-Anon** [comment]
Yes I tried to add a perspective transform for a similar purpose. Pretty much you would specify a x,y transform for each corner of the picture, like a free-transform. But the results were nothing like this, the system isn't contextually aware of what is going on.
