### ISSUE TITLE
No example usage

### ISSUE THREAD

**Issue by superskirv** [Animator-Anon/animator_extension#4]
Not sure what format I should be typing the `time_s | prompt | positive_prompts | negative_prompts` Do I type time_1 for 1 second, or do I need to do time_01? 

To zoom out with transform `time_s | transform | zoom | x_shift | y_shift | rotation` do I type | zoom | out? or | zoom | .5
Examples of each command usage would be nice, even if its just on the readme in github.

**Comment by Animator-Anon** [comment]
Yes, it is something i had on the script, but not here. I have added a very basic example, will pad it out properly in the future.

As a short answer, you'd do something like this:
0   | template | black and white, silent film, film grain | low quality, cropped
0   | transform | 2 | 0 | 0 | 0
0   | prompt | Shot of a sleeping person, possibly the narrator, in a dreamlike state | 
8   | prompt | Shot of a bright sun being extinguished, symbolizing the loss of hope |
16  | prompt | Close-up shot of stars wandering aimlessly in the darkness of space |
24  | prompt | Close-up shot of the barren and desolate landscape, with no sign of life or movement |
32  | prompt | Wide shot of the icy and dark earth, spinning in the moonless air |

The last prompt applied at time = 32s.
