### ISSUE TITLE
ValueError: Query/Key/Value should all have the same dtype

### ISSUE THREAD

**Issue by y0himba** [Animator-Anon/animator_extension#4]
Not sure if this is a bug or some interaction with an extension and settings, so posting here to ask for advice. I am using the `Animator` tab which is created by the excellent and aptly named `Animator Extension`

When trying to create an animation, I get the following error. This is just the last bit, there are quite a few lines with it, showing what line of code the errors are generated from. I can post those if needed. Text walls are bad, mmmkay? Please go easy on me, I'm an old fart.

```
ValueError: Query/Key/Value should all have the same dtype
  query.dtype: torch.float32
  key.dtype  : torch.float32
  value.dtype: torch.float16
```
Any help is appreciated.

**Comment by y0himba** [comment]
I figured this one out. Settings-->Stable Diffusion
![image](https://user-images.githubusercontent.com/11462603/217601580-60edcaef-2b7f-4f25-8085-fee389fc099f.png)

**Comment by Animator-Anon** [comment]
Yeah that doesn't look like an error in my script, I haven't messed with any of those settings. I have a newer card so I guess the go is to leave everything as float16 since they are optimised for it.
You have it all fixed now? If not, post the wall-o-text and I'll see if it's my fault.
