### ISSUE TITLE
Not working anymore despite reinstalling (all my other extensions work as today)

### ISSUE THREAD

**Issue by omegabrain** [Animator-Anon/animator_extension#6]
Hi, very nice extension, congrats for the nice work, here's what I've got in the console each time I launch Auto1111 :

Error executing callback ui_tabs_callback for C:\SD 2.1\stable-diffusion-webui\extensions\animator_extension\scripts\animator.py
Traceback (most recent call last):
  File "C:\SD 2.1\stable-diffusion-webui\modules\script_callbacks.py", line 105, in ui_tabs_callback
    res += c.callback() or []
  File "C:\SD 2.1\stable-diffusion-webui\extensions\animator_extension\scripts\animator.py", line 248, in on_ui_tabs
    prompt_interpolation, tmpl_pos, style_pos, tmpl_neg, style_neg = ui_block_processing()
  File "C:\SD 2.1\stable-diffusion-webui\extensions\animator_extension\scripts\animator.py", line 167, in ui_block_processing
    value=next(iter(shared.prompt_styles.styles.keys())))
StopIteration

The Animator tab doesn't appear anymore ofc. 
Thanks for help :)

**Comment by Animator-Anon** [comment]
Hmm do you have any saved styles in the UI? If not it could explain it. try create one, see if that helps.
In the mean time I'll try harden the code a bit.

**Comment by Animator-Anon** [comment]
Or maybe your styles.csv file has bad stuff in it? Either way try latest version.

**Comment by omegabrain** [comment]
Hi, I didn't edit my styles.csv but yes I have embeddings in my embeddings folder, that's not compatible with your extension u think ?

**Comment by omegabrain** [comment]
Re, so nice, your fixing script in your last update do the job ! well done dude :D

**Comment by Animator-Anon** [comment]
I just added a thing to catch any errors getting the list of styles. If there is one that's bugged, it will probably not work. but at least the extension works again. Odd, since I copied that code from WebUI in the first place.
