### ISSUE TITLE
How do I know the duration of  my video?

### ISSUE THREAD

**Issue by DenisKen** [Animator-Anon/animator_extension#7]
![image](https://user-images.githubusercontent.com/15076521/218287805-1a52c5e9-e337-4736-ad40-f959bfe044fc.png)
The label is not showing it. There's a way to do this calculation mannually?

I have 181 frames. The Output FPS and Speed is 12 x5 = 60 FPS

**Comment by Animator-Anon** [comment]
The duration should be set in the UI. The video will be a render of all the output frames, and FPS will be set to either what you input, or a calculated number if smoothing frames are used.
So the resulting video duration should very closely match the specified duration.

If smoothing frames are used, it gets trickier as frames are added in between every incoming frame.
resulting FPS = FPS + smoothing frame count * (FPS - 1)

FILM has it's own style of adding frames, it seems to do it in passes. Each pass adds a new frame in-between every existing frame. I try and calculate that in the code somewhere.

I'll try figure out why the FPS is unreported.
