### ISSUE TITLE
Error during final editing of video frames file

### ISSUE THREAD

**Issue by PonyCor** [Animator-Anon/animator_extension#8]
![!PONuy](https://user-images.githubusercontent.com/119464067/220481026-f429c81d-7cd1-482f-a08c-bf6eb2c20a0d.png)
Good afternoon, please help with my problem, maybe you have a couple of thoughts on a possible solution. The problem is that everything is generated normally, everything goes well until at the very end it starts rendering it already a video file, and I clearly understand that there is some problem with the JSOND module, but I don't have enough experience to understand how to fix it 3:

**Comment by Animator-Anon** [comment]
You need FFMPEG installed and available in the path environment variable. You can manually add it to the path system environment variable so you can run it from anywhere in command prompt.
